#并发数
concurrency: 5
#等待*秒后没有新任务则工作协程关闭
duration: 10
url: "https://wx.chenzao.com/v1/my/getphoto"
method: "post"
headers:
  Content-Type: "application/json"
  User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImV4cCI6MTcxNDUyNzQ3NSwiaWF0IjoxNzEzOTIyNjc1fQ==.kPM0UCwKCo7XYJa7fKLjxuF6+g2unvvWiFucDznOY7E="
  u-id: "{{}}"
request: ""
response:
  code: 200
  data:
    - "\"code\":100"
    - "\"data\":"
#变量定义
variables:
  code:
    source: "1234567890"
    #固定长度
    length: 4
